### ISSUE TITLE
[chapter 13] Retrieve the external IP address of a worker instance

### ISSUE THREAD

**Issue by TomicaKaniski** [salaxander/kubernetes-the-hard-way#12]
Should be:
EXTERNAL_IP=$(az vm show --show-details -g kubernetes-the-hard-way -n worker-0 --output tsv | cut -f20)

**Comment by pelleo** [comment]
Alternatively:
EXTERNAL_IP=$(az vm show --show-details -g kubernetes-the-hard-way -n worker-0 --query publicIps --output tsv)

**Comment by salaxander** [comment]
@pelleo This is a great suggestion! Thank you!

**Comment by salaxander** [comment]
Fixed with recent push
