### ISSUE TITLE
[chapter 13] SSH into the worker node

### ISSUE THREAD

**Issue by TomicaKaniski** [salaxander/kubernetes-the-hard-way#13]
Should be:
EXTERNAL_IP=$(az vm show --show-details -g kubernetes-the-hard-way -n ${INSTANCE_NAME} --output tsv | cut -f20)

**Comment by salaxander** [comment]
I wonder if this changed with a CLI update, it was definitely working before. In any case, I'll get it updated across the tutorial

**Comment by TomicaKaniski** [comment]
I guess so. Thanks!

**Comment by salaxander** [comment]
Fixed with recent push
