### ISSUE TITLE
[Chapter 03] Default Limit of vCPUs on Azure is 10. 12 Needed for Chapter.

### ISSUE THREAD

**Issue by t-eckert** [salaxander/kubernetes-the-hard-way#14]
## Issue

The default limit of vCPUs in a region is 10. This chapter requires 12 to be created. This causes the creation of `worker-2` to fail.

![image](https://user-images.githubusercontent.com/29112081/63220610-58006780-c140-11e9-8c56-1b88acdec7d9.png)

If the user submits the request to create this worker within the iterated series. The request will fail silently. If the user submits the request to create the worker independently, they will receive the following error: 

``` text
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'vm_deploy_5rAXEbqdNbfTEgfZ0S4u5i6R2SMKCvJO' is not valid according to the validation procedure. The tracking id is 'XXXXXXXXXXXXXXXXXXXX'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
Exception Details:
        Error Code: QuotaExceeded
        Message: Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 10, Additional requested: 2. Please read more about quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/{"subId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","pesId":"XXXXX","supportTopicId":"32447243"}.
```

## Possible Solution

Increasing the limit is not exceptionally difficult, but does require submitting a support ticket and knowing how to interpret the error above correctly. It may be helpful to have a note in the section on creating workers that describes this potential issue and how to fix it.

**Comment by t-eckert** [comment]
Docs Reference: https://docs.microsoft.com/en-us/azure/azure-supportability/resource-manager-core-quotas-request

**Comment by salaxander** [comment]
Thanks @t-eckert , I'll have a think about the best way to handle this
