### ISSUE TITLE
[chapter 03] cannot connect via SSH

### ISSUE THREAD

**Issue by TomicaKaniski** [salaxander/kubernetes-the-hard-way#4]
After creating the SSH config file, I cannot SSH into the machine because of wrong permissions (working inside WSL in my case):

tomica@N1:~/.ssh$ ssh controller-0
Bad owner or permissions on /home/tomica/.ssh/config

Fix:
chmod 644 ~/.ssh/config

**Comment by salaxander** [comment]
Thanks for pointing this out! I'll get it updated :)
