### ISSUE TITLE
[chapter 03] cannot connect via SSH (config file not created as it should be)

### ISSUE THREAD

**Issue by TomicaKaniski** [salaxander/kubernetes-the-hard-way#5]
There is an error in the line where you're cutting out the instance's public IP address:
az vm show --show-details -g kubernetes-the-hard-way -n ${instance} --output tsv | cut -f19

Should be:
az vm show --show-details -g kubernetes-the-hard-way -n ${instance} --output tsv | cut -f20

**Comment by f1point2** [comment]
Not sure about this - cut -f19 returned the IP address for me; cut -f20 returned the resource group name.

**Comment by TomicaKaniski** [comment]
> Not sure about this - cut -f19 returned the IP address for me; cut -f20 returned the resource group name.

What is the version of your Azure CLI?
I'm running it inside Ubuntu WSL (18.04) and my versions are (maybe it's something there):
az --version
azure-cli                         2.0.71
command-modules-nspkg               2.0.3
core                              2.0.71
nspkg                              3.0.4
telemetry                          1.0.3
Python location '/opt/az/bin/python3'
Extensions directory '/home/tomica/.azure/cliextensions'
Python (Linux) 3.6.5 (default, Aug  8 2019, 03:51:02) [GCC 7.4.0]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

**Comment by f1point2** [comment]
Looks like my Azure CLI needs an update (but I'm always wary in case it breaks something!). All on RHEL 8:

azure-cli                         2.0.69 *
command-modules-nspkg               2.0.3
core                              2.0.69 *
nspkg                              3.0.4
telemetry                          1.0.3

**Comment by salaxander** [comment]
This no longer relies on the cut and instead uses a query for the IP address
