### ISSUE TITLE
[chapter 03] creating the config file for SSH - wrong indentation

### ISSUE THREAD

**Issue by TomicaKaniski** [salaxander/kubernetes-the-hard-way#6]
Should be (EOF should be pulled out, in the same column with "done"; if not, shell waits for additional input):
for instance in controller-0 controller-1 controller-2 worker-0 worker-1 worker-2; do
  EXTERNAL_IP=$(az vm show --show-details -g kubernetes-the-hard-way -n ${instance} --output tsv | cut -f20)
  cat <<EOF | tee -a ~/.ssh/config
  Host ${instance}
  User azureuser
  HostName ${EXTERNAL_IP}
  IdentityFile ~/.ssh/id_rsa
  ServerAliveInterval 120
EOF
done

**Comment by t-eckert** [comment]
Worth noting. I also ran into this.

**Comment by f1point2** [comment]
I found that cut -f19 worked for me. cut-20 returned the resource group name.

**Comment by salaxander** [comment]
Should be fixed with recent commit
