### ISSUE TITLE
[chapter 04] creating certificates for workers - wrong cuts

### ISSUE THREAD

**Issue by TomicaKaniski** [salaxander/kubernetes-the-hard-way#8]
It should be cut -f20 and cut -f17 (otherwise you'll get the wrong fields):
EXTERNAL_IP=$(az vm show --show-details -g kubernetes-the-hard-way -n ${instance} --output tsv | cut -f20)
INTERNAL_IP=$(az vm show --show-details -g kubernetes-the-hard-way -n ${instance} --output tsv | cut -f17)

**Comment by salaxander** [comment]
Fixed with recent commit
