### ISSUE TITLE
[chapter 04] missing EOF in The Controller Manager Client Certificate

### ISSUE THREAD

**Issue by TomicaKaniski** [salaxander/kubernetes-the-hard-way#9]
Missing the EOF in The Controller Manager Client Certificate:
cat > kube-controller-manager-csr.json <<EOF
{
  "CN": "system:kube-controller-manager",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "system:kube-controller-manager",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

**Comment by salaxander** [comment]
Fixed with recent commit
